// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPDemDDrhMufR1PE5Q2zfNQN3_wcbSdU',
    appId: '1:486228667948:web:c1954aa8baad9f2a386b89',
    messagingSenderId: '486228667948',
    projectId: 'sirkulara-14669',
    authDomain: 'sirkulara-14669.firebaseapp.com',
    storageBucket: 'sirkulara-14669.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPa3MqZx-zGw13Gfoo60Q4TWFJ5Kb1To8',
    appId: '1:486228667948:android:b8bb058fd3dc7285386b89',
    messagingSenderId: '486228667948',
    projectId: 'sirkulara-14669',
    storageBucket: 'sirkulara-14669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoKhWrBikjOZnQ6cnMbgNp1zRilu2eJWQ',
    appId: '1:486228667948:ios:4e714891bc469a4d386b89',
    messagingSenderId: '486228667948',
    projectId: 'sirkulara-14669',
    storageBucket: 'sirkulara-14669.firebasestorage.app',
    iosBundleId: 'com.sirkulara.app',
  );
}
